Fix image urls
FACT-Finder-Web-Components/demos pull request #20
Opened 2019-06-27 15:53 UTC by toarm

2019-06-28 05:41 UTC, wdutkiewicz-obj commented
I think ff-navifation\damoData.js also needs modification - it is adjusted to 7.2

2019-06-28 05:43 UTC, ghost requested changes
Check for references to version 7.2 in ff-navigation\demoData.js file.

2019-07-01 11:45 UTC, toarm commented
> Check for references to version 7.2 in ff-navigation\demoData.js file.

Just checked out the file. The url prefix in the response file is neglectable. The code will strip of the "FACT-Finder-7.2" from the search params and use the url configured in `<ff-communication>`

2019-07-01 11:52 UTC, ghost approved these changes

2019-07-01 12:11 UTC, merged